### ISSUE TITLE
Using system interpreter

### ISSUE THREAD

**Issue by Tirpitz93** [intercept/intercept-python#4]
Would it be possible to use the system interpreter and using named pipe communication (or similar) to the intercept process?
This would remove the versioning complexity and would only require the `PYTHON` system path variable to be set, this could also be overridden on a per plugin/mod basis if specific versions are required (multiple python versions in the same arma installation).
I am not sure about the complexity or performance implications of this approach.

**Comment by dedmen** [comment]
>Would it be possible to use the system interpreter and using named pipe communication (or similar) to the intercept process?

That is not how this works. The Intercept process is Arma. And this is a Intercept plugin meaning it's process is also Arma. The interpreter is integrated into the plugin.

**Comment by jonpas** [comment]
Can we stop populating issue tracker with design questions and ideas? Please join Intercept Slack for that, issue tracker is not the place for this.

**Comment by Tirpitz93** [comment]
What I am suggesting is starting a new process for the python interpreter, then communicating with it using a named pipe.
This would remove the bus width shenanigans, as well as the embedding issues.

**Comment by jonpas** [comment]
https://github.com/intercept/intercept-python/issues/2#issuecomment-380094151
